version: 2

jobs:
  build:
    docker:
      # Primary container
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Compile
          command: make
      - run:
          name: Move artifacts
          command: |
            mkdir -p ~/results
            mv src/cv.pdf ~/results
            mv src/resume.pdf ~/results
            mv src/coverletter.pdf ~/results
      - store_artifacts:
          path: ~/results
